name: Deploy gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.20.1'

      - name: Install dependencies
        run: npn install

      - name: Create Publish Folder
        run: |
            rm -rf public
            mkdir -p public
            cp *.html *.js *.css node_modules public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: deploy
          commit_message: ${{ github.event.head_commit.message }}
